name: task_rahmanda_one
description: Test Flutter Phase One

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^0.2.4
  firebase_core: ^0.5.0+1
  cupertino_icons: ^1.0.2
  flutter_ds_bfi: ^0.0.1+26
  flutter_bloc: ^6.1.3
  crypto: ^3.0.0
  connectivity: ^2.0.2
  dio: ^3.0.10
  equatable: ^1.2.6
  firebase_messaging: ^7.0.3
  oktoast: ^2.3.2
  flutter_local_notifications: ^4.0.1+2
  imei_plugin: ^1.2.0
  indonesia: ^1.0.1
  json_annotation: ^4.0.1
  json_serializable: ^4.0.2
  rxdart: ^0.25.0
  device_information: ^0.0.2
  shared_preferences: ^0.5.12+4
  package_info: ^0.4.3+2
  sqflite: ^1.3.2+4
  table_calendar: ^2.3.3
  camera: ^0.5.8+11
  flutter_image_compress: ^0.7.0
  exif: ^1.0.3
  path_provider: ^1.6.24
  geolocator: ^6.1.4
  permission_handler: ^5.1.0+2
  analyzer: ^0.41.2
  intl: ^0.16.1
  countup: ^0.1.3
  geocoder: ^0.2.1
  app_settings: ^4.0.4
  image_picker: ^0.6.7+22
  image: ^3.0.1
  
  flutter_jailbreak_detection: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
  fonts:
    - family: Poppins
      fonts:
        - asset: packages/flutter_ds_bfi/fonts/Poppins-Regular.ttf
        - asset: packages/flutter_ds_bfi/fonts/Poppins-Bold.ttf
        - asset: packages/flutter_ds_bfi/fonts/Poppins-Italic.ttf
        - asset: packages/flutter_ds_bfi/fonts/Poppins-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

